version: '3'
services:
  web:
   image: nginx
   volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - /var/www:/var/www
    - ./logs/nginx:/var/log/nginx
   ports:
    - 80:80
    - 443:443
   restart: always
  jenkins:
    image:jenkins.nginx.docker:lts
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
